name: Cleanup Preview

on:
  workflow_call:

jobs:
  cleanup:
    runs-on: arc-runner-set
    steps:
    - uses: actions/checkout@v4
    - uses: azure/setup-kubectl@v3
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y unzip 
    - uses: azure/setup-helm@v3
      id: install

    - name: Uninstall Release
      run: |
        helm uninstall "site-pr-${{ github.event.pull_request.number }}" \
          --namespace arkmodding 
